cache: cargo
language: rust
rust:
  - beta
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo +nightly fmt --all -- --check
  - cargo +nightly clippy
  - cargo build --all
  - cargo test --all

branches:
  only:
  - master

