cache: cargo
language: rust
rust:
  - nightly
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo +nightly fmt --all -- --check
  - cargo build --verbose --all
  - cargo test --verbose --all

branches:
  only:
  - master

