[package]
name = "pathfinder"
version = "0.5.4"
authors = ["pontus"]
include = ["src/**/*", "Cargo.toml"]
description = "Create nodes, clusters of nodes and connection in between."
repository = "https://github.com/pontuslae/pathfinder"
readme = "README.md"
keywords = ["nodes", "image", "pathing"]
categories = ["visualization", "text-processing"]
license = "MIT"

[dependencies]
rand = "0.6.1"
gif = "0.10.1"
image = "0.20.1"
pythagoras = "0.1.1"
