[package]
name = "pathfinder"
version = "0.5.2"
authors = ["pontus"]
include = ["src/**/*", "Cargo.toml"]
description = "A small library to create nodes, groups of nodes and connection in between them utilizing the image crate."
repository = "https://github.com/pontuslae/pathfinder"
readme = "README.md"
keywords = ["nodes", "image"]
categories = ["visualization", "text-processing"]
license = "MIT"

[dependencies]
rand = "0.3"
gif = "0.10.1"
image = "0.20.0"
pythagoras = "0.1.1"
