[package]
name = "pathfinder"
version = "0.2.1"
authors = ["pontus"]
exclude = [
    "*.png",
    "*.jpg",
]
description = "A small library to create nodes, groups of nodes and connection in between them utilizing the image crate."
repository = "https://github.com/pontuslae/pathfinder"
readme = "README.md"
keywords = ["nodes", "image"]
categories = ["visualization", "text-processing"]
license = "GPL-3.0-only"

[dependencies]
rand = "0.3"
image = "*"
